### ISSUE TITLE
Create Interactive CLI for Basic UAC Example

### ISSUE THREAD

**Issue by hyperioxx** [KalbiProject/kalbi#112]
ability to start calls with CLI 

```
kalbiclient> call 0123456789
```

**Comment by raghu-pyr** [comment]
@DeWarner I understand you are working in this. Just wanted to let you know I am eager to pitch in if you need any help.

**Comment by DeWarner** [comment]
@raghu-pyr I am happy for you to take the helm on this one, I havent got any progress to share, happy to provide guidance if needed.

**Comment by raghu-pyr** [comment]
@DeWarner Thanks. I am new to Go so I am going to take some time before I can do any meaningful contribution. Hoping to make some progress with your help.  Will get back to you soon with my queries. Thanks again
