### ISSUE TITLE
A typo Report

### ISSUE THREAD

**Issue by mjcsrx** [KalbiProject/Kalbi#117]
In the directory "/ transport / factory. Go", lines 20 and 26 use "UDP" instead of the corresponding protocol

**Comment by hyperioxx** [comment]
tcp and tls are yet to be implemented... it's just a place holder for now i guess

**Comment by mjcsrx** [comment]
OK, I'm still a novice. Forgive me for my abruptness.

**Comment by hyperioxx** [comment]
it wasn't abrupt it was a good spot !! you are more than welcome to contribute :)
