### ISSUE TITLE
A strange looking question

### ISSUE THREAD

**Issue by mjcsrx** [KalbiProject/Kalbi#118]
In line 82 of "/ SIP / dialog / dialog. Go",It is not clear why the new object "return new (dialogmanager)" is returned instead of the existing object "diagmng"
//NewDialogManager returns new Dialog Manager
func NewDialogManager() *DialogManager {
	diagMng := new(DialogManager)

	diagMng.dialogs = make(map[string]Dialog)
	diagMng.Lock = &sync.RWMutex{}
	return new(DialogManager)
}

**Comment by hyperioxx** [comment]
Your right! Oversight on my behalf, Feel free to fix !!

**Comment by hyperioxx** [comment]
@mjcsrx looks like peter picked it up :)
